[package]
name = "flechasdb"
version = "0.0.1"
edition = "2021"
default-run = "flechasdb"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
rand = "0.8"
